### ISSUE TITLE
Filters vs. extractors

### ISSUE THREAD

**Issue by tsalo** [tyarkoni/featureX#44]
I'm implementing A-weighting, which filters the audio timeseries, and I was thinking about differentiating filters and extractors. It seems almost wasteful to create an event for every frame in an audio stream, and filters seem like they'd be used to preprocess data rather than to generate timelines. 

If filters are sufficiently different, they may merit another submodule along with extractors and stimuli.

Thoughts?

**Comment by tyarkoni** [comment]
+1 for filters. But I think it's worth spending some time thinking about what that API would look like, because we want to avoid having two different interfaces for filter and extractors. We might want to think about moving to a scikit-learn-like interface, where every `Filter` or `Extractor` ultimately boils down to a `transform` call somewhere. So we could have `Transformer` as the base class, and `Filter` and `Extractor` are differentiated by the fact that a `Filter` always returns an instance of the same type, whereas an `Extractor` returns a `Value`, `Event`, or `Timeline`. (Though the latter is also problematic, because it's kind of clunky to return variable types, which is what we do right now.)

**Comment by tyarkoni** [comment]
Closing this, as it's (mostly) addressed in #49.
